env: local
evaluate:
  weights: weights/best.pt
judge:
  conf_threshold: 0.5
  iou_threshold: 0.45
  review_band:
  - 0.3
  - 0.5
kfold:
  k: 2
  random_state: 42
kfold_tune:
  batch: 8
  bgr: 0.00516
  box: 7.87952
  cache: ram
  close_mosaic: 0
  cls: 0.37333
  cls_pw: 0.02866
  copy_paste: 0.0
  cutmix: 0.00106
  degrees: 0.01553
  device: cpu
  dfl: 1.91088
  epochs: 2
  fliplr: 0.23179
  flipud: 0.00033
  hsv_h: 0.023
  hsv_s: 0.45353
  hsv_v: 0.66066
  imgsz: 640
  lr0: 0.00302
  lrf: 0.01199
  mixup: 0.00123
  model: weights/yolo26s.pt
  momentum: 0.80234
  mosaic: 1.0
  patience: 100
  perspective: 0.0
  scale: 0.29856
  shear: 0.0
  translate: 0.09454
  warmup_epochs: 4.48591
  warmup_momentum: 0.95
  weight_decay: 0.00053
paths:
  colab:
    project_root: /content/pcb-defect-inspection
    raw_data: dataset/PCBData
  local:
    project_root: C:\Users\compu\OneDrive\Desktop\mirroring\ati3_project\runs\_verify_kfold_tune
    raw_data: dataset/PCBData
  server:
    project_root: .
    raw_data: dataset/PCBData
preprocess:
  img_size: 1280
split:
  random_state: 42
  test: 0.1
  train: 0.7
  val: 0.2
train:
  batch: 16
  cache: ram
  device: 0
  epochs: 500
  imgsz: 1280
  model: weights/yolo26s.pt
  patience: 100
train_tune:
  batch: 16
  bgr: 0.0148
  box: 10.32546
  cache: ram
  close_mosaic: 10
  cls: 0.66305
  cls_pw: 0.00289
  copy_paste: 0.00164
  cutmix: 0.00419
  degrees: 0.00153
  device: 0
  dfl: 1.49476
  epochs: 500
  fliplr: 0.19774
  flipud: 0.00264
  hsv_h: 0.01517
  hsv_s: 0.75373
  hsv_v: 0.24641
  imgsz: 1280
  lr0: 0.00685
  lrf: 0.01249
  mixup: 0.01208
  model: weights/yolo26s.pt
  momentum: 0.90303
  mosaic: 0.60328
  patience: 100
  perspective: 0.0
  scale: 0.16703
  shear: 0.00119
  translate: 0.01077
  warmup_epochs: 3.06163
  warmup_momentum: 0.62303
  weight_decay: 0.00065
tune:
  batch: -1
  cache: ram
  device: 0
  epochs: 100
  imgsz: 1280
  iterations: 100
  model: weights/yolo26s.pt
  patience: 30
